Get method added
metaregistrar/rdap-client pull request #11
Opened 2019-11-08 00:19 UTC by luizgb

Minor changes, few get methods created.

2019-11-08 06:59 UTC, chaos0815 commented on src/Data/RdapEntity.php
> +                                $this->vcards[] = new RdapVcard($card[0], $card[1], $card[2], $card[3]);
reverting the previous fix will generate errors again.
It is not safe to assume $card is an array.

2019-11-08 07:04 UTC, chaos0815 commented on src/Data/RdapEntity.php
> +        //if (isset($this->port43)) {
Why should this be commented out?

2019-11-08 07:05 UTC, chaos0815 commented on src/Data/RdapEntity.php
> +            return $this->handle[0];
What about the other handles? Why only return the first?

2019-11-08 07:06 UTC, chaos0815 commented on src/Data/RdapEntity.php
> +    public function getPort43() {
Please leave return types as they help harden the code.

2019-11-08 07:08 UTC, chaos0815 commented on src/Data/RdapEntity.php
> +    public function getEntities() {
Please add docBlocks and return types where applicable

2019-11-08 07:08 UTC, chaos0815 requested changes
See annotations

2019-11-08 07:30 UTC, chaos0815 requested changes

2019-11-08 07:30 UTC, chaos0815 commented on src/Data/RdapLink.php
> +            //print_r($content);
please remove debug code instead of commenting out.

2019-11-08 07:30 UTC, chaos0815 commented on src/Data/RdapLink.php
> +            if (isset($content[0])) {
this will not work. 
isset($content[0]) is also true when $content['rel'] is set.
So the else part will never be reached.

2019-11-08 07:30 UTC, chaos0815 commented on src/Data/RdapLink.php
> +    public function getType(): string {
so getTitle() is removed? Please explain.

2019-11-08 07:30 UTC, chaos0815 commented on src/Data/RdapPublicId.php
> +                $this->ids[$id['type']] = $id['identifier'];
At first glance this seems to overly simplify. 
Please elaborate.

2019-11-08 07:30 UTC, chaos0815 commented on src/Data/RdapPublicId.php
> -    /**
Please leave docBlocks

2019-11-08 07:30 UTC, chaos0815 commented on src/Data/RdapPublicId.php
> +    public function getIds(){
return type and docBlock

2019-11-08 07:30 UTC, chaos0815 commented on src/Data/RdapVcard.php
> -    /**
Not specific but better than nothing. Please leave dockBlock in code

2019-11-08 07:30 UTC, chaos0815 commented on src/Data/RdapVcard.php
> -    /**
Why do you hate docBlocks?

2019-11-08 08:50 UTC, merged

2019-11-08 15:12 UTC, chaos0815 commented
@metaregistrar did you look at the changes and regarded them as OK?

2019-11-11 21:19 UTC, metaregistrar commented
Many changes i just merge (when there is no harm done) and then download into my favourite IDE to look  at them and maybe fix something here and there. I find the tools of Github insufficient to really check if changes are correct or not.

By the way, the RDAP project was created by me about 5 years ago (when RDAP was only just invented) to see if i could understand and process the protocol. I am happy that the code is now used by various people. but for myself i have not found a real application for this project yet. Maybe when all ccTLD's have also adopted RDAP, then we will use this project also within our own company.

2019-11-12 08:15 UTC, chaos0815 commented
I'm sorry to say that with this low bar of standards, I can not continue to work on this project.
I've put quite some time and money of my employer into getting this code up to today's standards as far as possible and inside budget. 
Seeing that code flows in without any level of acceptance criteria, I cannot endorse this anymore.